name: Build Vimkey website
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          CLEAN: true
          BRANCH: gh-pages
          FOLDER: dist/
